### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by joseywoermann** [joseywoermann/PyBenchmark#1]
- [ ] Get familiar with PyGame

- [ ] Develop a concept for a benchmark

- [ ] implement a score-system

**Comment by joseywoermann** [comment]
- [ ] Do a lot of testing and comparing to determine the effectiveness of the benchmark

- [ ] maybe add a comparison-chart to my website
